version: '3.8'

services:
  react:
    build:
      context: ./  # Build context is now the root directory
    environment:
      - CHOKIDAR_USEPOLLING=true # For create-react-app <= 5.x
      - WATCHPACK_POLLING=true # For create-react-app >= 5.x
      - WDS_SOCKET_PORT=0 # The mapped port on your host machine

    ports:
      - '4000:4000'
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./:/usr/src/app  # Mount root directory
      - /usr/src/app/node_modules  # Avoid mounting node_modules from host
