version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/django # Updated to match Dockerfile's WORKDIR
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True' # Set to 'False' in production
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: 10.0.0.30
      DB_PORT: 5432

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - web
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=10.0.0.30:5432
      - GF_DATABASE_NAME=mydatabase
      - GF_DATABASE_USER=myuser
      - GF_DATABASE_PASSWORD=mypassword
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true
    restart: always

volumes:
  grafana_data:
