# Generated by Django 4.2.16 on 2024-09-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_people_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='years_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peopleprojects',
            name='years_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
